name: IaC Lifecycle

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:

    - name: Build step 00 - Checkout GitHub Repo
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Build step 01 - Checkout GitHub Repo
      uses: actions/checkout@v2

    - name: Build step 02 - Install dependencies
      run: npm install --omit=dev

    - name: Build step 03 - Install nest cli
      run: npm install -g @nestjs/cli

    - name: Build step 04 - Build
      run: npm run build

    - name: Build step 05 - Removing zip files
      run: rm -rf dist/*.zip

    - name: Build step 06 - Copy node_modules
      run: cp -r node_modules dist/

    - name: Build step 07 - Mkdir vaporeon
      run: mkdir vaporeon

    - name: Build step 08 - Zip dist
      run: cd dist && zip -r ../vaporeon/dist.zip .

    - name: Infrastructure step 01 - Terraform Install
      env :
        TERRAFORM_VERSION: "1.5.6"
      run : |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Infrastructure step 02 - Terraform Version
      run : terraform --version

    - name: Infrastructure step 03 - Set AWS Account
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : us-east-1

    - name: Infrastructure step 04 - Terraform Init
      run : terraform -chdir=./infrastructure init -input=false

    - name: Infrastructure step 05 - Terraform Validate
      run : terraform -chdir=./infrastructure validate

    - name: Infrastructure step 06 - Terraform Plan
      #run : terraform -chdir=./infrastructure plan -input=false -out tfplan
      run : terraform -chdir=./infrastructure plan -input=false -destroy -out tfplan

    - name: Infrastructure step 07 - Terraform Apply
      run : terraform -chdir=./infrastructure apply -auto-approve -input=false tfplan
